spring.application.name=Backend de Producto

spring.datasource.url=jdbc:postgresql://localhost:5432/product_db_g4
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# --- Configuración de seguridad JWT ---
# Clave secreta para firmar los tokens JWT. Es crucial mantener esta clave segura y en un entorno de producción debe ser una variable de entorno.
# Genera una clave segura de al menos 256 bits (por ejemplo, usando https://www.allkeysgenerator.com/)
jwt.secret=tu_clave_secreta_aqui_para_firmar_los_tokens_seguramente

# Tiempo de expiración del token JWT en segundos.
# En este ejemplo, el token expira en 3600 segundos (1 hora).
jwt.expiration=3600